knowledge_people/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
    path("admin/", admin.site.urls),
    path("users/", include("users.urls")),
    path("users/", include("django.contrib.auth.urls")),
    path('scholarships/',include('scholarships.urls',namespace="scholarships")),
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

scholarships/urls.py
from django.urls import path
from users.views import BeneficiaryUpdateView
from . import views
from .views import NewDonation, TransactionListView,ScholarshipListView,DonationsListView, ContactView 
from .views import InstitutionListView

app_name = 'scholarships'

urlpatterns = [path("showmenu/", views.ShowMenu.as_view(), name="showmenu"), 
               path("newapplication/", views.NewApplication.as_view(), name="newapplication"),
               path("lookapplications/", views.LookApplication.as_view(), name="lookapplication"),
               path("insertScholarship/", views.InsertScholarship.as_view(), name="insertScolarship"),
                path('beneficiaries/<int:pk>/update/', views.BeneficiaryUpdateView.as_view(), name='beneficiary_profile_update'),
                path('naturaldonor/<int:pk>/update/', views.NaturalDonorUpdateView.as_view(), name='natural_donor_profile_update'),
                path('legaldonor/<int:pk>/update/', views.LegalDonorUpdateView.as_view(), name='legal_donor_profile_update'),
                path('institution/<int:pk>/update/', views.InstitutionUpdateView.as_view(), name='institution_profile_update'),
                path("soli_Activa/", views.ActiveSolicitud.as_view(), name="soli_Activa"),
                path("editSolicitudActiva/", views.EditSolicitud.as_view(), name='editSolicitudActiva'),
                path("newdonation/", NewDonation.as_view(), name='newdonation'),
                path("lookbeneficiaries/", views.LookBeneficiaries.as_view(), name='look_beneficiaries'),
                path("lookdonors/", views.LookDonors.as_view(), name='look_donors'),
                path('aliados/', InstitutionListView.as_view(), name='aliados'),
                path("lookInstitutios/", views.LookInstitutions.as_view(), name='look_institutions'),
                path("filtersemester/<int:id>/", views.FilterSemester.as_view(), name='filtersemester'),
                path("filterinstitution/<int:id>/", views.FilterInstitution.as_view(), name='filterinstitution'),
                path("filterprogram/<str:program_name>/", views.FilterProgram.as_view(), name='filterprogram'),
                path("filtercity/<str:city>/", views.FilterCity.as_view(), name='filtercity'),
                path("filtertype/<str:typeI>/", views.FilterTypeI.as_view(), name='filtertype'),
                path("searchIns",views.SrchView.as_view(),name='searchIns'),
                path("searchBen",views.SrchBenView.as_view(),name='searchBen'),
                path('filtervalue/<int:min_value>/<int:max_value>/', views.FilterInterval.as_view(), name='filtervalue'),
                path('showdetailsBen/<int:id>/', views.ShowDetailsBen.as_view(), name='showdetailsbeneficiary'),
                path('showdetailsIns/<int:id>/', views.ShowDetailsIns.as_view(), name='showdetailsinstitucion'),
                path('transactions/', TransactionListView.as_view(), name='transaction-list'),
                path('donations/', DonationsListView.as_view(), name='donationslist'),
                path('payments/<int:id>/', views.Payments.as_view(), name='payments'),
                path('paymentsBen/<int:id>/', views.PaymentsBen.as_view(), name='paymentsBen'),
                path('paymentpaypal/<int:id>/', views.PaymentsPaypal.as_view(), name='paymentpaypal'),
                path('paymentcard/<int:id>/', views.PaymentsCard.as_view(), name='paymentcard'),
                path('paymentpse/<int:id>/', views.PaymentsPse.as_view(), name='paymentpse'),
                path('pay1/<int:id>/', views.Pay1.as_view(), name='pay1'),
                path('pay2/<int:id>/', views.Pay2.as_view(), name='pay2'),
                path('pay3/<int:id>/', views.Pay3.as_view(), name='pay3'),
                path('donationIns/<int:id>/', views.DonationIns.as_view() , name='donationIns'),
                path('donationSch/<int:id>/', views.DonationSch.as_view() , name='donationSch'),
                path('typeSch/<int:id>/<int:x>/', views.TypeSch.as_view() , name='typeSch'),
                path('scholarships/', ScholarshipListView.as_view(), name='scholarships'),

                path('contact/', ContactView.as_view(), name='contact_view'),
                

                path("showmenu/", views.ShowMenuList.as_view(), name="showmenu"), 

                
               ]

users/urls.py
from django.urls import path
from . import views
from .views import UserListView, AllUserListView
from .views import InstitutionVerifyView
from .views import InstitutionRejectVerificationView

app_name = 'users'

urlpatterns = [path("signupBen/", views.SignUpBen.as_view(), name="signupb"), 
               path("signupDon/", views.SignUpDon.as_view(), name="signupd"),
               path("signupLegalDon/", views.SignUpLegalDon.as_view(), name="signupld"),  
               path("signupIns/", views.SignUpIns.as_view(), name="signupi"),
               path("sigin/", views.SigIn.as_view(),name="sigin"), 
               path("menu/", views.SigIn.as_view(),name="menu"), 
                path('beneficiaries/<int:pk>/update/', views.BeneficiaryUpdateView.as_view(), name='beneficiary_update'),
                path('naturaldonors/<int:pk>/update/', views.NaturalDonorUpdateView.as_view(), name='natural_donor_update'),
                path('legaldonors/<int:pk>/update/', views.LegalDonorUpdateView.as_view(), name='legal_donor_update'),
                path('institutions/<int:pk>/update/', views.InstitutionUpdateView.as_view(), name='institution_update'),
                path('institutions/', UserListView.as_view(), name='user_list'),
                path('users/institutions/<int:pk>/verify/', InstitutionVerifyView.as_view(), name='verify_institution'),
                path('users/institutions/<int:pk>/reject-verification/', InstitutionRejectVerificationView.as_view(), name='reject_verification'),
                path('users/', AllUserListView.as_view(), name='showUsers'),]   
                

users/models.py
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from .managers import UserManager

class Notification(models.Model):
    content = models.CharField(max_length=255)
    is_read = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.content
    

class User(AbstractBaseUser, PermissionsMixin):
    username=None
    BENEFICIARY=1
    NATURALDONOR=2
    LEGALDONOR=3
    INSTITUTION=4
    ADMIN=5

    ROLE_CHOICE=(
          (BENEFICIARY, 'Beneficiario'),
          (NATURALDONOR,'Donante natural'),
          (LEGALDONOR,'Donante juridico'),
          (INSTITUTION,'Institución'),
          (ADMIN,'Admin'),
    )

    TI=1
    CC=2
    CE=3
    NIT=4

    IDTYPE_CHOICE= ((TI,'Tarjeta de Identidad'),
                (CC,'Cédula de Ciudadanía'),
                ( CE,'Cédula extranjera'),
                (NIT,'NIT'))
    email = models.EmailField(_("email address"), unique=True)
    name=models.CharField(max_length=100,null=False)
    profilePicture= models.ImageField(upload_to="users",null=True, blank=True)
    idType = models.PositiveSmallIntegerField(choices=IDTYPE_CHOICE,null=False)
    numID = models.CharField(max_length=10,null=False)
    role=models.PositiveSmallIntegerField(choices=ROLE_CHOICE,null=False)

    date_joined = models.DateTimeField(auto_now_add=True)
    last_login= models.DateTimeField(auto_now_add=True)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now_add=True)
    contact = models.CharField(max_length=15)
    notifications = models.ManyToManyField(Notification)


    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_superadmin = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
   
    date_joined = models.DateTimeField(default=timezone.now)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ['name', 'idType', 'numID', 'role']

    objects = UserManager()

    def __str__(self):
        return self.email
     
    def has_module_perms(self, app_label):
       return self.is_superuser
    def has_perm(self, perm, obj=None):
       return self.is_superuser
    
class Admin(User):
    pass
    def __str__(self):
        return self.name
    class Meta:
        verbose_name = 'Admin'

class NaturalDonor(User):
    pass

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = 'NaturalDonor'

class LegalDonor(User):
    description = models.TextField(max_length=255)
    organization_type_choices = (
        ('foundation', 'Fundación o Beca'),
        ('company', 'Empresa o Empleador'),
        ('alumni_association', 'Asociación de Exalumnos'),
        ('charity', 'Organización Benéfica o Sin Fines de Lucro'),
        ('community_organization', 'Organización Comunitaria'),
        ('mentoring_program', 'Programa de Tutoría o Mentoría'),
        ('religious_organization', 'Organización Religiosa'),
        ('government', 'Gobierno u Organismo Público'),
    )
    organization_type = models.CharField(
        max_length=50,
        choices=organization_type_choices,
    )


    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = 'LegalDonor'

class Beneficiary(User):
    # beneficiary specific fields
    birth_date = models.DateField()
    optionsGender = (('F','Femenino'),
                     ('M','Masculino'),
                     ('O','Otro'))
    gender = models.CharField(max_length=15,choices=optionsGender,null=False) 

    def __str__(self):
        return self.name + " email: " + self.email    
    
    class Meta:
        verbose_name = 'Beneficiary'
        verbose_name_plural = 'Beneficiaries'


class Institution(User):

    description = models.TextField(max_length=255)
    TYPE_CHOICES = (
        ('Tecnica', 'Tecnica'),
        ('Tecnologica', 'Tecnologica'),
        ('Pregrado', 'Pregrado'),
        ('Posgrado','Posgrado')
    )
    type_institution = models.CharField(
        max_length=255,
        blank = False,
    )
    address = models.CharField(max_length=100)
    city = models.CharField(max_length=70)
    money_donation = models.IntegerField(default=0)

    optionsstate= (('A','Aprobada'),
                     ('P','Pendiente'),
                     ('R','Rechazada'))
    verificationState = models.CharField(max_length=30,choices=optionsstate,null=False, default='P')


   

users/templates/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dreams Bank</title>
    <link href="{% static '_base.css' %}" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">

    <!--Carrusel-->
    <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
	  <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap" rel="stylesheet">
	  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet">
	  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
	

</head>
<body>
   <div class="container-fluid">
    <nav class="navbar navbar-expand-lg">
        <div class="container">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav mx-auto">
            <a class="navbar-brand mx-auto" href="#"><img src="../../media/icons/dreamsbank.jpeg" width="194" height="140"></a>
            <a class="navbar-brand mx-auto" href="#" style=margin-top:2px; ><img src="../../media/images/Logo_KnowledgePeople.jpg" width="200" height="140"></a>
            <li class="nav-item align-self-end">
                <a class="nav-link active" aria-current="page" href="#">Nosotros</a>
              </li>
              <li class="nav-item align-self-end">
                <a class="nav-link" href="/../scholarships/aliados/">Aliados</a>
              </li>
              <li class="nav-item align-self-end">
                <a class="nav-link" href="/../scholarships/contact/">Contacto</a>
              </li>

              <li class="nav-item dropdown align-self-end">
                <a class="nav-link dropdown-toggle" id="register" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Registrarse
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="/../users/signupBen">Beneficiario</a></li>
                  <li><a class="dropdown-item" href="/../users/signupDon">Donante Natural</a></li>
                  <li><a class="dropdown-item" href="/../users/signupLegalDon">Donante Juridico</a></li>
                </ul>
              </li>
              <li class="nav-item align-self-end">
                <a class="nav-link" href="/../users/sigin" id="login">Iniciar Sesión</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>

      {% block content %}
      {% endblock %}
      <br>
      <br>
      <div class=row>
        <footer class="footer" style="background-color: #FFFF;">
            <div class="container">
              <div class="row">
                <div class="col-md-4">
                  <h5><i></i> Contacto</h5>
                  <p>Para más información, contáctanos:</p>
                  <ul class="list-unstyled">
                    <li><i class="fas fa-phone"></i> Teléfono: +123456789</li>
                    <li><i class="fas fa-envelope"></i> Email: dreamsbank.kp@gmail.com</li>
                    <li><i class="fas fa-map-marker-alt"></i> Dirección: Calle Principal, Ciudad, País</li>
                  </ul>
                </div>
                <div class="col-md-4">
                  <h5>Política de privacidad</h5>
                  <ul class="list-unstyled">
                    <li><a href="/politica-privacidad">Política de privacidad</a></li>
                    <li><a href="/terminos-condiciones">Términos y condiciones</a></li>
                    <li><a href="/cookies">Política de cookies</a></li>
                  </ul>
                </div>
                <div class="col-md-4">
                  <h5>Síguenos en nuestras redes sociales</h5>
                  <ul class="list-inline social-icons">
                    <li class="list-inline-item"><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                    <li class="list-inline-item"><a href="#"><i class="fab fa-twitter"></i></a></li>
                    <li class="list-inline-item"><a href="#"><i class="fab fa-instagram"></i></a></li>
                  </ul>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-md-12 text-center">
                  <p>&copy; 2023 Dreams Bank - Knowledge People. Todos los derechos reservados.</p>
                </div>
              </div>
            </div>
          </footer>
        </div>
   </div>

  <script src="https://kit.fontawesome.com/df6c844774.js" crossorigin="anonymous"></script>
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
</body>
</html>

users/templates/home.html
{% extends '_base.html' %}
{% load static %}

{% block title %}Home{% endblock %}

{% block content %}
<link href="{% static 'home.css' %}" rel="stylesheet">
<link href="{% static '_base.css' %}" rel="stylesheet">
{% if user.is_authenticated %}
  Welcome, {{ user.email }}!
  <script>
    window.location.href = "{% url 'scholarships:showmenu' %}";
  </script>

  <p><a href="{% url 'logout' %}">Log Out</a></p>
{% else %}
<section class="container-fluid " id="rowb">
  <div class="row w-100 mx-auto" id="imageb" >
      <div class="col-lg-6 text-center">
          <p id="text0">
              <span class="p1"> La plataforma </span>
               <br>
               <span class="p2">donde tus sueños </span>
               <br>
               <span class="p3">se hacen realidad </span>
           </p>
           <p id="text1">
               Publica tu solicitud de beca y cumple <br> tu sueño de estudiar o realiza una <br> donación y haz feliz a un estudiante. 
           </p>

           <button type="button" class="btn" id="donatebtn">
            <a href="/../users/signup"  class="text-white text-decoration-none">Realizar <br> donacion</a>
            </button>
           <button type="button" class="btn">
            <a href="/../users/signup"  class="text-white text-decoration-none" >Solicitar <br> beca</a>
          </button>
      </div>
      <div class="col-lg-3" id="col1">
          <img class="img-thumbnail" src="../media/icons/Image_Ref1.png" alt="No Encontrada" id="imagega"/>
      </div>
      <div class="col-lg-3">
          <img class="img-thumbnail" src="../media/icons/Image_Ref2.png" alt="No Encontrada" id="imagega"/>
      </div>
  </div>
</section>
{% endif %}
{% endblock %}

users/templates/login.html
{% extends '_base.html' %}
{% load static %}
{% block title %}Inicio de sesión{% endblock %}

{% block content %}
<link href="{% static 'login.css' %}" rel="stylesheet">
<link href="{% static '_base.css' %}" rel="stylesheet">
<section class="container-fluid " id="rowb">
  <div class="row w-100 mx-auto" id="rowb">
    <div class="col-lg-6 d-none d-lg-block bgimage" id="colimg">
      <img src="../../media/icons/stud.png"  class="img-fluid d-none d-md-block" id="imgex">
    </div>
    <div class ="col-lg-6 px-5 ">

      <h3 class="text-center py-5 mt-5">Inicio de Sesión</h3>

          <form class=" form-control-sm mt-5" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn" id="registerbtn">Iniciar sesión</a></button>
        </form>

      </div>
  </div>
</section>
<div class="row" id="additional-row">
  <!-- Aquí puedes agregar contenido adicional -->
  <br>
  <br>
</div>

{% endblock %}

users/templates/showUsers.html
{% extends 'base.html' %} {% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>HistoryApp</title>
    <link
      href="https://fonts.googleapis.com/css?family=Open+Sans:400,600,300"
      rel="stylesheet"
      type="text/css"
    />
    <!-- Bootstrap CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ"
      crossorigin="anonymous"
    />
  </head>
  <body>
    {% block content %}
    <link href="{% static '/historyapplications.css' %}" rel="stylesheet" />
    <link href="{% static 'newscholarship.css' %}" rel="stylesheet" />

    <div class="row mb-3 flex-sm-row" id="contTitulo">
      <div class="col-md-8">
        <br />
        <h1 id="titulo" class="mt-2" style="color: white">Instituciones aliadas</h1>
        <hr id="line" class="w-80" />
      </div>
      <div class="col-md-4">
        <img
          src="../../media/icons/HigherEducation.png"
          alt="No Encontrada"
          class="img-fluid d-none d-md-block"
          id="graduatedImg"
        />
      </div>
    </div>

    <form method="GET" action="">
        <label for="role-filter">Filter by Role:</label>
        <select id="role-filter" name="role">
            <option value="">All</option>
            <option value="1">Beneficiario</option>
            <option value="2">Donante natural</option>
            <option value="3">Donante jurídico</option>
            <option value="4">Institución</option>
            <option value="5">Admin</option>
        </select>
        <button type="submit">Filter</button>
    </form>


    <!--  Container -->
<!-- user_list.html -->

<h1>Lista de usuarios</h1>
<ul>
    {% for user in users %}
        <li>{{ user.name }} - {{ user.get_role_display }}</li>
    {% empty %}
        <li>No users found.</li>
    {% endfor %}
</ul>


    {% endblock %}
  </body>
</html>

users/templates/signup.html
{% extends '_base.html' %}
{% load static %}
{% block title %}Registro{% endblock %}

{% block content %}

<link href="{% static 'signup.css' %}" rel="stylesheet">
<link href="{% static '_base.css' %}" rel="stylesheet">

</div class="container-fluid">

<div class="container-lg"> <!--Container White with border Black-->
    <div class="row g-3 mt-3">
        <div class="col-6"> <!--Form column-->
            <div class="row">
                <div class="col-12" id="titleDreamsBank"> <!--Title-->
                    <p>Dreamsbank</p>
                </div>
                <div class="col-12">
                    <p id="subtitleCreateAccount">
                        Crear tu cuenta de DreamsBank
                    <p>
                </div>
                <div class="col-6">
                    <p id="mandatoryObligatory"> <img src="../../media/icons/Asterisk.png" alt="Asterisk image"
                            width="10" height="10" id="AsteriskImg" /> Obligatorio</p>
                </div>
            </div>
            <form method="post"  enctype=multipart/form-data>
              {% csrf_token %}
              {{ form.as_p }}
              <button type="submit" id="registersingup">Registrarse</button>
            </form>  
          </div> 
        <div class="col-6" id="icon-Lema">
            <div class="row">
                <div class="col-12">
                    <img src="../../media/icons/dreamsbank.jpeg" class="img-fluid" alt="No Encontrada" width="224"
                        height="144" id="iconLema" />
                </div>
            </div>
            <div class="row">
                <div class=col-12>
                    <p>
                        <span id="p1"> La plataforma </span>
                        <br>
                        <span id="p2">donde tus sueños </span>
                        <br>
                        <span id="p3">se hacen realidad </span>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/user_update.html
{% extends 'base.html' %}

{% block content %}
  <h1>Editar Perfil</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit"  class="btn btn-success form-control">Actualizar</button>
  </form>
{% endblock %}

users/templates/usersList.html
{% extends 'base.html' %} {% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>HistoryApp</title>
    <link
      href="https://fonts.googleapis.com/css?family=Open+Sans:400,600,300"
      rel="stylesheet"
      type="text/css"
    />
    <!-- Bootstrap CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ"
      crossorigin="anonymous"
    />
  </head>
  <body>
    {% block content %}
    <link href="{% static '/historyapplications.css' %}" rel="stylesheet" />
    <link href="{% static 'newscholarship.css' %}" rel="stylesheet" />

    <div class="row mb-3 flex-sm-row" id="contTitulo">
      <div class="col-md-8">
        <br />
        <h1 id="titulo" class="mt-2" style="color: white">Instituciones aliadas</h1>
        <hr id="line" class="w-80" />
      </div>
      <div class="col-md-4">
        <img
          src="../../media/icons/HigherEducation.png"
          alt="No Encontrada"
          class="img-fluid d-none d-md-block"
          id="graduatedImg"
        />
      </div>
    </div>

    <!--  Container -->
    {% if users %}
<!-- user_list.html -->
{% for user in users  %}
<tr class="mt-4 align-middle" style="height: 7rem;" >
  <td class="align-middle" style="border-top-left-radius: 10px; border-bottom-left-radius: 10px;">
    {% if user.profilePicture != "" %}
    <img src="/media/{{ user.profilePicture }}" class="img-fluid" alt="noimage"
      style="max-width: 3rem; max-height: 3rem; border-radius: 10px; margin-right: 0.5rem;">
    {% else %}
    <img src="/media/users/profile_default.png" class="img-fluid" alt="noimage"
      style="max-width: 3rem; max-height: 3rem; border-radius: 10px; margin-right: 0.5rem;">
    {% endif %}
  </td>
  <td>
    <div class="row">
      <div class="col-12" style="font-weight: bolder; font-size: larger;">{{ user.name|capfirst }}
      </div>
      <div class="col-12"></div>
      <div class="col-12">{{ user.institution.city }}</div>
    </div>
  </td>
  <td>
    <div class="row">
        <div class="col-12">
            {% for choice in user.TYPE_CHOICES %}
            {% if choice.0 in user.type_institution %}
            <div class="form-check">
              <input class="form-check-input" type="checkbox" name="type_institution_checkbox" value="{{ choice.0 }}"
                {% if choice.0 in user.type_institution %} checked {% endif %}>
              <label class="form-check-label">
                {{ choice.1 }}
              </label>
            </div>
          {% endif %}
            {% endfor %}
        </div>
        <style>
            .form-check-input:checked {
            background-color:#A4D955;
            border: none;
            }
        </style>
      </div>
  </td>
  <td>
    <div class="row my-auto">
      <div class="col-12 text-center">Recaudado</div>
      <div class="col-12 text-center">$ {{ user.money_donation }}</div>
    </div>
  </td>
  <td
    style="background-color: rgba(242, 159, 5, 0.7); border-top-right-radius: 10px; border-bottom-right-radius: 10px;"
    class="align-middle">
    <div class="d-flex align-items-center justify-content-center">
      <button type="submit" class="btn btn-link p-0" style=" border: none;" name="viewBeneficiaryDetails"
        data-scholarship-id="{{ user.id_user.name }}">
        <a href="{% url 'scholarships:showdetailsinstitucion' id=user.id %}">
        <img src="/media/images/Forward.png" class="img-fluid" alt="noimage"
          style="max-width: 3rem; max-height: 3rem;">
        </a>
      </button>
    </div>
  </td>
</tr>
{% endfor %}


<!--<h1>Lista de usuarios de tipo institución:</h1>
<ul>
  {% for user in users %}
    <li>{{ user.name }} - {{ user.email }} - {{ user.institution.verificationState }}</li>
    {% if user.institution.verificationState == 'P' %}
    <a href="{% url 'users:verify_institution' pk=user.institution.pk %}">Verificar</a>
    <a href="{% url 'users:reject_verification' pk=user.institution.pk%}">Rechazar Verificación</a>
    {% endif %}
  {% endfor %}
</ul>-->

    {% else %}

    <div class="row justify-content-center" style="min-height: 85vh">
      <div class="col align-self-center text-center">
        <p style="font-weight: 600; font-size: 24px">
          No hay instituciones aliadas
        </p>
      </div>
    </div>

    {% endif %}

    {% endblock %}
  </body>
</html>