knowledge_people/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
    path("admin/", admin.site.urls),
    path("users/", include("users.urls")),
    path("users/", include("django.contrib.auth.urls")),
    path('scholarships/',include('scholarships.urls',namespace="scholarships")),
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

scholarships/urls.py
from django.urls import path
from users.views import BeneficiaryUpdateView
from . import views
from .views import NewDonation, TransactionListView,ScholarshipListView,DonationsListView, ContactView 
from .views import InstitutionListView

app_name = 'scholarships'

urlpatterns = [path("showmenu/", views.ShowMenu.as_view(), name="showmenu"), 
               path("newapplication/", views.NewApplication.as_view(), name="newapplication"),
               path("lookapplications/", views.LookApplication.as_view(), name="lookapplication"),
               path("insertScholarship/", views.InsertScholarship.as_view(), name="insertScolarship"),
                path('beneficiaries/<int:pk>/update/', views.BeneficiaryUpdateView.as_view(), name='beneficiary_profile_update'),
                path('naturaldonor/<int:pk>/update/', views.NaturalDonorUpdateView.as_view(), name='natural_donor_profile_update'),
                path('legaldonor/<int:pk>/update/', views.LegalDonorUpdateView.as_view(), name='legal_donor_profile_update'),
                path('institution/<int:pk>/update/', views.InstitutionUpdateView.as_view(), name='institution_profile_update'),
                path("soli_Activa/", views.ActiveSolicitud.as_view(), name="soli_Activa"),
                path("editSolicitudActiva/", views.EditSolicitud.as_view(), name='editSolicitudActiva'),
                path("newdonation/", NewDonation.as_view(), name='newdonation'),
                path("lookbeneficiaries/", views.LookBeneficiaries.as_view(), name='look_beneficiaries'),
                path("lookdonors/", views.LookDonors.as_view(), name='look_donors'),
                path('aliados/', InstitutionListView.as_view(), name='aliados'),
                path("lookInstitutios/", views.LookInstitutions.as_view(), name='look_institutions'),
                path("filtersemester/<int:id>/", views.FilterSemester.as_view(), name='filtersemester'),
                path("filterinstitution/<int:id>/", views.FilterInstitution.as_view(), name='filterinstitution'),
                path("filterprogram/<str:program_name>/", views.FilterProgram.as_view(), name='filterprogram'),
                path("filtercity/<str:city>/", views.FilterCity.as_view(), name='filtercity'),
                path("filtertype/<str:typeI>/", views.FilterTypeI.as_view(), name='filtertype'),
                path("searchIns",views.SrchView.as_view(),name='searchIns'),
                path("searchBen",views.SrchBenView.as_view(),name='searchBen'),
                path('filtervalue/<int:min_value>/<int:max_value>/', views.FilterInterval.as_view(), name='filtervalue'),
                path('showdetailsBen/<int:id>/', views.ShowDetailsBen.as_view(), name='showdetailsbeneficiary'),
                path('showdetailsIns/<int:id>/', views.ShowDetailsIns.as_view(), name='showdetailsinstitucion'),
                path('transactions/', TransactionListView.as_view(), name='transaction-list'),
                path('donations/', DonationsListView.as_view(), name='donationslist'),
                path('payments/<int:id>/', views.Payments.as_view(), name='payments'),
                path('paymentsBen/<int:id>/', views.PaymentsBen.as_view(), name='paymentsBen'),
                path('paymentpaypal/<int:id>/', views.PaymentsPaypal.as_view(), name='paymentpaypal'),
                path('paymentcard/<int:id>/', views.PaymentsCard.as_view(), name='paymentcard'),
                path('paymentpse/<int:id>/', views.PaymentsPse.as_view(), name='paymentpse'),
                path('pay1/<int:id>/', views.Pay1.as_view(), name='pay1'),
                path('pay2/<int:id>/', views.Pay2.as_view(), name='pay2'),
                path('pay3/<int:id>/', views.Pay3.as_view(), name='pay3'),
                path('donationIns/<int:id>/', views.DonationIns.as_view() , name='donationIns'),
                path('donationSch/<int:id>/', views.DonationSch.as_view() , name='donationSch'),
                path('typeSch/<int:id>/<int:x>/', views.TypeSch.as_view() , name='typeSch'),
                path('scholarships/', ScholarshipListView.as_view(), name='scholarships'),

                path('contact/', ContactView.as_view(), name='contact_view'),
                

                path("showmenu/", views.ShowMenuList.as_view(), name="showmenu"), 

                
               ]

users/urls.py
from django.urls import path
from . import views
from .views import UserListView, AllUserListView
from .views import InstitutionVerifyView
from .views import InstitutionRejectVerificationView

app_name = 'users'

urlpatterns = [path("signupBen/", views.SignUpBen.as_view(), name="signupb"), 
               path("signupDon/", views.SignUpDon.as_view(), name="signupd"),
               path("signupLegalDon/", views.SignUpLegalDon.as_view(), name="signupld"),  
               path("signupIns/", views.SignUpIns.as_view(), name="signupi"),
               path("sigin/", views.SigIn.as_view(),name="sigin"), 
               path("menu/", views.SigIn.as_view(),name="menu"), 
                path('beneficiaries/<int:pk>/update/', views.BeneficiaryUpdateView.as_view(), name='beneficiary_update'),
                path('naturaldonors/<int:pk>/update/', views.NaturalDonorUpdateView.as_view(), name='natural_donor_update'),
                path('legaldonors/<int:pk>/update/', views.LegalDonorUpdateView.as_view(), name='legal_donor_update'),
                path('institutions/<int:pk>/update/', views.InstitutionUpdateView.as_view(), name='institution_update'),
                path('institutions/', UserListView.as_view(), name='user_list'),
                path('users/institutions/<int:pk>/verify/', InstitutionVerifyView.as_view(), name='verify_institution'),
                path('users/institutions/<int:pk>/reject-verification/', InstitutionRejectVerificationView.as_view(), name='reject_verification'),
                path('users/', AllUserListView.as_view(), name='showUsers'),]   
                

scholarships/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(max_length=100)
    phone = forms.CharField(max_length=11)
    email = forms.EmailField()
    message = forms.CharField(widget=forms.Textarea)

scholarships/views.py
from django.views import View
from django.shortcuts import get_object_or_404, render
from users.models import Beneficiary, Institution, User, Notification
from .models import Scholarship,Transaction, PartialTransaction
from datetime import datetime
from django.db.models import Q

from django.views.generic import TemplateView, ListView,DetailView

from django.views.generic import TemplateView, ListView
from django.shortcuts import redirect



from users.views import BeneficiaryUpdateView,NaturalDonorUpdateView,LegalDonorUpdateView,InstitutionUpdateView

class ShowMenu(View):
    def get(self,request):
        return render(request,'menu.html')
    
class ShowMenuList(View):
    def get(self,request):
        userInstitution = request.user
        idInst = request.user.id
        scholarshipList = []
        allScholarships = Scholarship.objects.filter(institution = idInst, active = 'AC')

        for i in reversed(allScholarships):
            if len(scholarshipList) <= 5:
                scholarshipList.append(allScholarships.index(i))

        context = {
            'userInstitution': userInstitution,
            'scholarshipList':scholarshipList
        }
        return render(request,'menu.html',context)


        


class NewApplication(View):
    def get(self,request):
        institutions = Institution.objects.all()
        data = {'institutions':institutions}

        id_ben = request.user.id
        datos_solicitud = Scholarship.objects.filter(id_user = id_ben, active = 'AC')
        solicitud = datos_solicitud.first()

        if(solicitud == None):
            return render(request,'newscholarship.html',data)
        else:
            return render(request,'errorCreateNewScholarship.html')

class LookApplication(View):
    def get(self,request):
        id_ben = request.user.id
        scholarship = Scholarship.objects.filter(id_user=id_ben)
        data = {"scholarships":scholarship}
        return render(request,'historyapps.html',data)
    
class ActiveSolicitud(View):
     def get(self,request):
        id_ben = request.user.id
        datos_solicitud = Scholarship.objects.filter(id_user = id_ben, active = 'AC')
        solicitud = datos_solicitud.first()
        institutions = Institution.objects.all()

        if(solicitud != None):
            contexto = {
                'solicitud_activa': solicitud,
                'institutions': institutions,
            }
            return render(request, 'ActiveSolicitud.html', contexto)
        else:
            return render(request,'errorActiveScholarship.html')
    
class InsertScholarship(View):
    def post(self,request):
        if request.method == 'POST':
            name = request.POST['nombres']
            email = request.POST['correo']
            typedocument = request.POST['tipoid']
            numdoc = request.POST['numdoc']
            institute = request.POST['instituc']
            institutionvalue = Institution.objects.get(name=institute)
            program = request.POST['programa']
            valuesem = request.POST['valorS']
            timeA = request.POST['periodoActual']
            totalP = request.POST['totalPeriodos']
            icfes = request.POST['puntajeI']
            levels = request.POST['estrato']
            optionnew = request.POST['ingresoEstudiante']
            try:
                picturedoc = request.FILES['src-file1']
                picturecer = request.FILES['src-file2']
            except:
                print('error')

        
            now = datetime.now()
            letter = request.POST['cartaMotivacional']
            id_ben = request.user.id
            ben = Beneficiary.objects.get(user_ptr_id=id_ben)

            if not Scholarship.objects.filter(id_user=id_ben, active='AC').exists():
                scolarship = Scholarship(stratum=levels,photocopy_id=picturedoc, motivational_letter=letter,
                                        certificate=picturecer,value_period=valuesem,icfes_score=icfes,period_current=timeA,
                                        program_adm=program,application_type=optionnew,state='Pendiente',
                                        total_periods=totalP,active='AC',date_application=now,id_user=ben,institution=institutionvalue)
                scolarship.save()

                return render(request,'menu.html')
            else:
                scolarship = Scholarship(stratum=levels,photocopy_id=picturedoc, motivational_letter=letter,
                                        certificate=picturecer,value_period=valuesem,icfes_score=icfes,period_current=timeA,
                                        program_adm=program,application_type=optionnew,state='Pendiente',
                                        total_periods=totalP,active='IN',date_application=now,id_user=ben)
                scolarship.save()
  
                return render(request,'menu.html')

class EditSolicitud(View):
    def get(self,request):
        id_ben = request.user.id
        datos_solicitud = Scholarship.objects.filter(id_user=id_ben, active='AC')
        solicitud = datos_solicitud.first()
        institutions = Institution.objects.all()

        contexto = {
            'solicitud_activa': solicitud,
            'institutions': institutions,
        }
        return render(request, 'editionScholarship.html', contexto)

    def post(self,request):
        if request.method == 'POST':

            if 'inactivate_scholarship' in request.POST:
                id_ben = request.user.id
                solicitud = Scholarship.objects.filter(id_user=id_ben, active='AC')
                scholarshipToInactivate = solicitud.first()

                scholarshipToInactivate.active = 'IN'
                scholarshipToInactivate.state = 'Rechazada'
                scholarshipToInactivate.save()
                print(f"Solicitud del usuario {scholarshipToInactivate.id_user.name} ha sido inactivada.")
                return render(request, 'menu.html')

            institute = request.POST['instituc']
            program = request.POST['programa']
            valuesem = request.POST['valorS']
            timeA = request.POST['periodoActual']
            totalP = request.POST['totalPeriodos']
            icfes = request.POST['puntajeI']
            levels = request.POST['estrato']
            optionnew = request.POST['ingresoEstudiante']
            picturedoc = None
            picturecer = None
            try:
                picturedoc = request.FILES['src-file1']
                picturecer = request.FILES['src-file2']
            except:
                print('error')

            now = datetime.now()
            letter = request.POST['cartaMotivacional']

            id_ben = request.user.id
            solicitud = Scholarship.objects.filter(id_user=id_ben, active='AC')
            scholarshipUpdated = solicitud.first()

            scholarshipUpdated.stratum = levels
            scholarshipUpdated.photocopy_id = picturedoc if picturedoc != None else scholarshipUpdated.photocopy_id
            scholarshipUpdated.motivational_letter = letter
            scholarshipUpdated.certificate = picturecer if picturecer != None else scholarshipUpdated.certificate
            scholarshipUpdated.value_period = valuesem
            scholarshipUpdated.icfes_score = icfes
            scholarshipUpdated.period_current = timeA
            scholarshipUpdated.program_adm = program
            scholarshipUpdated.application_type = optionnew
            scholarshipUpdated.total_periods = totalP
            scholarshipUpdated.date_application = now
            institution = get_object_or_404(Institution, id=institute)
            scholarshipUpdated.institution = institution

            scholarshipUpdated.save()
            return render(request, 'menu.html')


class LookBeneficiaries(ListView):
    def get(self, request):
        semester = []
        for i in range(1,13):
            semester.append(i)

        intervals = [(0,2000000),(2000001,5000000),(5000001,10000000),(10000001,20000000),(20000000,50000000)]
        institutions = Institution.objects.all()
        scholarships = Scholarship.objects.all()
        data = {'semesters':semester,'scholarships':scholarships,'institutions':institutions,'intervals':intervals}
        return render(request, 'lookbeneficiaries.html',data)


class LookDonors(ListView):
    def get(self, request):
        id_ben = request.user.id
        donations = Transaction.objects.filter(scolarship_donation__id_user=id_ben)

        user = User.objects.get(id=id_ben)
        notifications = user.notifications.all()

        for notification in notifications:
            notification.is_read = True
            notification.save()

        data = {'donations':donations}
        return render(request, 'lookdonors.html',data)


class FilterSemester(ListView):
    def get(self,request,id):
        semester = []
        for i in range(1,13):
            semester.append(i)
        
        intervals = [(0,2000000),(2000001,5000000),(5000001,10000000),(10000001,20000000),(20000000,50000000)]
        institutions = Institution.objects.all()
        scholarships = Scholarship.objects.filter(period_current=id)
        data = {'scholarships':scholarships,'semesters':semester,'institutions':institutions,'intervals':intervals}
        return render(request,'lookbeneficiaries.html',data)
## Edit Profile

class FilterInstitution(ListView):
    def get(self, request, id):
        semester = []
        for i in range(1,13):
            semester.append(i)

        intervals = [(0,2000000),(2000001,5000000),(5000001,10000000),(10000001,20000000),(20000000,50000000)]
        actualinst = Institution.objects.get(id=id)
        institutions = Institution.objects.all()
        scholarships = Scholarship.objects.filter(institution=actualinst)
        data = {'scholarships':scholarships,'semesters':semester,'institutions':institutions,'intervals':intervals}

scholarships/templates/institutionDetails.html
{% extends 'base.html' %} {% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Descripción de institucion para aportar</title>
    <link href="{% static '/beneficiaryToDonate.css' %}" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600,300" rel="stylesheet" type="text/css" />
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous" />

    {% block header %}
    <link href="{% static '/beneficiaryToDonate.css' %}" rel="stylesheet" />
    {% endblock %}
</head>

<body>
    {% block content %}
    <div class="container-fluid">
    <div class="row mb-3 flex-sm-row" id="contTitulo">
        <div class="col-md-9">
            <br />
            <h3 id="titulo" class="mt-2">Detalle de Institucion</h3>
            <hr id="line" class="w-80" />
        </div>
        <div class="col-md-3 text-center">
            <div class="d-flex justify-content-center">
            <img src="../../../media/icons/fund.png" alt="No Encontrada" class="img-fluid d-none d-md-block"
                id="graduatedImg" />
            </div>
        </div>
    </div>


    <!--- fields form-->
    <div class="form">
        <div class="row">
            <div class="col-lg-5 d-flex flex-column align-items-center " >
                <img src="/media/{{ institution.profilePicture }}" class="img-fluid" alt="noimage"
                  style="max-width: 15rem; height: 13rem; border-radius: 10px; margin-right: 0.5rem;">


                
               
            </div>

            <div class="col-lg-7">
                <div class="d-flex ">
                    <h5 style="color: #F29F05;">Institucion: </h5>
                    <h5 class="mx-2"> 
                    {{ institution.name|capfirst }}
                    </h5>
                </div>
                <div class="d-flex ">
                    <h5 style="color: #F29F05;">Carreras: </h5>
                    <h5 class="mx-2">
                    {% for choice in institution.TYPE_CHOICES %}
                        {% if choice.0 in institution.type_institution %}
                         {{ choice.1 }},
                        {% endif %}
                        {% endfor %}

                    </h5>
                </div>
                <div class="d-flex ">
                    <h5 style="color: #F29F05;">Ciudad: </h5>
                    <h5 class="mx-2"> 
                    {{ institution.city }}
                    </h5>
                </div>
                <div class="d-flex ">
                    <h5 style="color: #F29F05;">Email: </h5>
                    <h5 class="mx-2"> 
                    {{ institution.email }}
                    </h5>
                </div>
                <div class="d-flex ">
                    <h5 style="color: #F29F05;">Direccion: </h5>
                    <h5 class="mx-2"> 
                    {{ institution.address }}
                    </h5>
                </div>
                <div class="d-flex ">
                    <h5 style="color: #F29F05;">Contacto: </h5>
                    <h5 class="mx-2"> 
                    {{ institution.contact }}
                    </h5>
                </div>
                
            </div>
        </div>
        <div class="row justify-content-center mt-5 mb-4">
            <div class="col-lg-10 d-flex flex-column align-items-center">
              <h5 style="text-align: left; color: #F29F05;">Descripcion</h5>
              <textarea class="form-control " rows="13" id="cartaMotivacional"
                        maxlength="2000" value="" readonly style="border: 1.5px solid gray; border-radius:1rem">{{ institution.description }}</textarea>
            </div>
            <a type="submit" href="{% url 'scholarships:donationIns' institution.id %}" class="btn custom btn col-md-5 mt-4 mb-5" id="botonDonar">
                 Aportar
            </a>
          </div>
    </div>
    </div>
   
    {% endblock %}
    <!-- jQuery y Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
        crossorigin="anonymous"></script>
</body>

</html>

scholarships/templates/lookbeneficiaries.html
{% extends 'base.html' %} {% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Consultar Beneficiarios</title>
  {% block content %}
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600,300" rel="stylesheet" type="text/css" />
  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
  <link href="{% static '/lookbeneficiaries.css' %}" rel="stylesheet" />
</head>

<body>



  <div class="container-fluid">
    <form class="d-flex col=lg-12" action="{% url 'scholarships:searchBen' %}" method="post">
        {% csrf_token %}
      <div class="input-group">
      <input type="text" name="inputsearch"  class="form-control custom-input" placeholder="Buscar Beneficiario" aria-label="Buscar"
      style="font-weight: bolder;" >
    
      <div class="input-group-append">
      <button style="
      border: none; background-color: transparent;" type="submit">
      <span class="input-group-text search-icon">
        <i class="fas fa-search"></i>
      </span>
      </button>
      </div>
      </div>
    </form>


    <!-- Filters -->
    <div class="row d-flex justify-content-center">
      <div class="d-flex justify-content-center mt-3" style=" width:auto;">
        <div class="dropdown text-center ">
          <button class="btn dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false"
            style="background-color: white; border: 0.5px solid #A4D955;">
            Valor Sem.
          </button>
          <ul class="dropdown-menu ">
            {% for interval in intervals %}
            <li><a class="dropdown-item text-center itemnumberp"
                href="{% url 'scholarships:filtervalue' interval.0 interval.1 %}">$ {{ interval.0 }} - $ {{ interval.1 }}</a></li>
            {% endfor %}
          </ul>
        </div>
      </div>
      <div class="d-flex justify-content-center mt-3" style="width: auto;">
        <div class="dropdown text-center">
          <button class="btn dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false"
            style="background-color: white; border: 0.5px solid #A4D955;">
            Institucion
          </button>
          <ul class="dropdown-menu">
            {% for institution in institutions %}
            <li><a class="dropdown-item itemnumberp" href="{% url 'scholarships:filterinstitution' institution.id %}">{{institution.name }}</a></li>
            {% endfor %}
          </ul>
        </div>
      </div>

      <div class="d-flex justify-content-center mt-3" style=" width: auto;">
        <div class="dropdown text-center">
          <button class="btn dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false"
            style="background-color: white; border: 0.5px solid #A4D955;">
            Programa
          </button>
          <ul class="dropdown-menu ">
            <li><a class="dropdown-item itemnumberp"
                href="{% url 'scholarships:filterprogram' 'ingenieria-informatica' %}">Ingeniería Informática</a></li>
            <li><a class="dropdown-item itemnumberp"
                href="{% url 'scholarships:filterprogram' 'administracion-empresas' %}">Administración de Empresas</a>
            </li>
            <li><a class="dropdown-item itemnumberp"
                href="{% url 'scholarships:filterprogram' 'medicina' %}">Medicina</a></li>
            <li><a class="dropdown-item itemnumberp"
                href="{% url 'scholarships:filterprogram' 'ingenieria-civil' %}">Ingeniería Civil</a></li>
            <li><a class="dropdown-item itemnumberp"
                href="{% url 'scholarships:filterprogram' 'psicologia' %}">Psicología</a></li>
            <li><a class="dropdown-item itemnumberp" href="{% url 'scholarships:filterprogram' 'derecho' %}">Derecho</a>
            </li>
            <li><a class="dropdown-item itemnumberp"
                href="{% url 'scholarships:filterprogram' 'ingenieria-industrial' %}">Ingeniería Industrial</a></li>
            <li><a class="dropdown-item itemnumberp"
                href="{% url 'scholarships:filterprogram' 'comunicacion-social' %}">Comunicación Social</a></li>

          </ul>
        </div>
      </div>
      <div class=" d-flex justify-content-center mt-3" style=" width: 9.5rem;">
        <div class="dropdown w-100 text-center">
          <button class="btn dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false"
            style="background-color: white; border: 0.5px solid #A4D955;">
            Semestre
          </button>
          <ul class="dropdown-menu w-100">
            {% for i in semesters %}
            <li><a class="dropdown-item text-center itemnumber " href="{% url 'scholarships:filtersemester' i %}"> {{ i }}</a></li>
            {% endfor %}
          </ul>
        </div>
      </div>
    </div>
    <style>
      .itemnumber:hover {
        color: white;
        background-color: #A4D955;
        font-weight: bolder;
      }

      .itemnumberp:hover {
        color: white;
        background-color: #A4D955;
        font-weight: 600;
      }

      .itemall {
        background-color: white;
        border: 1px solid #F29F05;
        border-radius: 1rem;
      }

      .itemn {
        color: #F29F05;
        font-weight: 600;
        text-decoration: none;
      }

      .itemn:hover {
        color: black;
        font-weight: 600;
        text-decoration: none;
      }

      .itemall:hover {
        background-color: white;
        border: 1px solid #a4d955;
        border-radius: 1rem;
      }
    </style>

    <!-- Beneficiaries -->
    <div class="row " style="background-color: white; margin-top:2rem">
      <div class="col-lg-8 d-flex">
        <h4 style="color: #F29F05; font-weight: bolder; margin-top: 2rem;">Consultar Beneficiarios</h4>
      </div>
      <div class="col-lg-4 align-self-end d-flex justify-content-end">

        <button class="btn itemall" type="button" aria-expanded="false">
          <a class="text-center itemn " href="{% url 'scholarships:look_beneficiaries' %}"> Ver todos </a>
        </button>

      </div>
      <div class="table-responsive" >
        <table class="table">
          <thead>
            <tr>
              <th></th>
              <th></th>
              <th></th>
              <th></th>
              <th style="width: 2rem"></th>
            </tr>
          </thead>
          <tbody>
            {% if scholarships %}
            {% for x in scholarships %}
            <tr class="mt-3 align-middle">
              <td class="align-middle" style="border-top-left-radius: 10px; border-bottom-left-radius: 10px;">
                {% if x.id_user.profilePicture != "" %}
                <img src="/media/{{ x.id_user.profilePicture }}" class="img-fluid" alt="noimage"
                  style="max-width: 3rem; max-height: 3rem; border-radius: 10px; margin-right: 0.5rem;">
                {% else %}
                <img src="/media/users/profile_default.png" class="img-fluid" alt="noimage"
                  style="max-width: 3rem; max-height: 3rem; border-radius: 10px; margin-right: 0.5rem;">
                {% endif %}
              </td>
              <td>
                <div class="row">
                  <div class="col-12" style="font-weight: bolder; font-size: larger;">{{ x.id_user.name|capfirst }}
                  </div>
                  <div class="col-12">{{ x.institution.name }}</div>
                  <div class="col-12">{{ x.institution.city }}</div>
                </div>
              </td>
              <td>
                <div class="row ">
                  <div class="col-12" style="font-weight: 700;">{{ x.period_current }}º</div>
                  <div class="col-12">{{ x.program_adm }}</div>
                </div>
              </td>
              <td>
                <div class="row my-auto">
                  <div class="col-12 text-center">Valor semestral</div>
                  <div class="col-12 text-center">$ {{ x.value_period }}</div>
                </div>
              </td>
              <td
                style="background-color: rgba(242, 159, 5, 0.7); border-top-right-radius: 10px; border-bottom-right-radius: 10px;"
                class="align-middle">
                <div class="d-flex align-items-center justify-content-center">
                  <button type="submit" class="btn btn-link p-0" style=" border: none;" name="viewBeneficiaryDetails"
                    data-scholarship-id="{{ x.id_user.name }}">
                    <a href="{% url 'scholarships:showdetailsbeneficiary' id=x.id %}">
                    <img src="/media/images/Forward.png" class="img-fluid" alt="noimage"
                      style="max-width: 3rem; max-height: 3rem;">
                    </a>
                  </button>
                </div>
              </td>
            </tr>
            {% endfor %}
            {% endif %}

          </tbody>
        </table>
      </div>

    </div>
  </div>

  {% endblock %}
</body>

</html>

scholarships/templates/report.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>REPORTEEEE</h1>
    {{ value }}
    <a href="{% url 'scholarships:showmenu' %}">Menu</a>
</body>
</html>